StageComputer/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace StageComputer.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

StageComputer/Pages/Index.cshtml.cs
using StageComputer.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using PublicHoliday;
using SpreadCheetah;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using OpenCloseDays.Models;
using OpenCloseDays;
using OpenCloseDays.Extensions;
using FluentValidation;

namespace StageComputer.Pages
{
    public class StageComputerModel : PageModel
    {
        #region Bound poperties
        [BindProperty(Name = "s", SupportsGet = true)]
        [Display(Name = "Date début")]
        public DateTime StartDate { get; set; } = DateTime.Now;

        [BindProperty(Name = "e", SupportsGet = true)]
        [Display(Name = "Date fin")]
        public DateTime EndDate { get; set; } = DateTime.Now;

        [BindProperty(Name = "monh", SupportsGet = true)]
        [Display(Name = "Lundi")]
        public int MondayWorkHours { get; set; } = 7;
        [BindProperty(Name = "monm", SupportsGet = true)]
        [Display(Name = "Lundi")]
        public int MondayWorkMinutes { get; set; } = 0;

        [BindProperty(Name = "tueh", SupportsGet = true)]
        [Display(Name = "Mardi")]
        public int TuesdayWorkHours { get; set; } = 7;
        [BindProperty(Name = "tuem", SupportsGet = true)]
        [Display(Name = "Mardi")]
        public int TuesdayWorkMinutes { get; set; } = 0;

        [BindProperty(Name = "wedh", SupportsGet = true)]
        [Display(Name = "Mercredi")]
        public int WednesdayWorkHours { get; set; } = 7;
        [BindProperty(Name = "wedm", SupportsGet = true)]
        [Display(Name = "Mercredi")]
        public int WednesdayWorkMinutes { get; set; } = 0;

        [BindProperty(Name = "thuh", SupportsGet = true)]
        [Display(Name = "Jeudi")]
        public int ThursdayWorkHours { get; set; } = 7;
        [BindProperty(Name = "thum", SupportsGet = true)]
        [Display(Name = "Jeudi")]
        public int ThursdayWorkMinutes { get; set; } = 0;

        [BindProperty(Name = "frih", SupportsGet = true)]
        [Display(Name = "Vendredi")]
        public int FridayWorkHours { get; set; } = 7;
        [BindProperty(Name = "frim", SupportsGet = true)]
        [Display(Name = "Vendredi")]
        public int FridayWorkMinutes { get; set; } = 0;

        [BindProperty(Name = "sath", SupportsGet = true)]
        [Display(Name = "Samedi")]
        public int SaturdayWorkHours { get; set; } = 0;
        [BindProperty(Name = "satm", SupportsGet = true)]
        [Display(Name = "Samedi")]
        public int SaturdayWorkMinutes { get; set; } = 0;

        [BindProperty(Name = "sunh", SupportsGet = true)]
        [Display(Name = "Dimanche")]
        public int SundayWorkHours { get; set; } = 0;
        [BindProperty(Name = "sunm", SupportsGet = true)]
        [Display(Name = "Dimanche")]
        public int SundayWorkMinutes { get; set; } = 0;


        [BindProperty(Name = "excl", SupportsGet = true)]
        public string? ExcludedDates { get; set; }


        [BindProperty(Name = "r", SupportsGet = true)]
        [Display(Name = "Montant horaire")]
        public string? PayRate { get; set; } = "0";

        [BindProperty(Name = "c", SupportsGet = true)]
        [Display(Name = "Pays")]
        public string? Country { get; set; } = "fr";
        [BindProperty(Name = "stc", SupportsGet = true)]
        public string? StageCountry { get; set; } = StageLegislation.IN_FRANCE;
        [BindProperty(Name = "ent", SupportsGet = true)]
        public string? EnterpriseType { get; set; } = StageLegislation.ENTERPRISE_TYPE_PRIVATE;
        [BindProperty(Name = "tt", SupportsGet = true)]
        public string? TrainingType { get; set; } = StageLegislation.TRAINING_OTHER;
        [BindProperty(Name = "wph", SupportsGet = true)]
        [Display(Name = "Si vous travaillez certains jours fériés, veuillez sélectionner ces jours")]
        public IEnumerable<string>? WorkPublicHolidays { get; set; } = Array.Empty<string>();
        #endregion

        public IEnumerable<SelectListItem> Countries { get; }
        public IEnumerable<SelectListItem> HolidayNames { get; private set; }
        public WorkDaysComputationResult Result { get; set; }

        public DateTime? LongStageStartDate { get; set; }

        private readonly ILogger<StageComputerModel> _logger;
        private readonly OpenCloseDaysService _openCloseDaysService;
        private readonly PlafondSecuFetcher plafondSecuFetcher;
        private readonly ExplainationManager explainationManager;
        private readonly IValidator<StageComputerModel> validator;
        private readonly PublicHolidaysService _publicHolidaysService;

        public StageComputerModel(
            ILogger<StageComputerModel> logger,
            OpenCloseDaysService openCloseDaysService,
            PlafondSecuFetcher plafondSecuFetcher,
            ExplainationManager explainationManager,
            IValidator<StageComputerModel> validator,
            PublicHolidaysService publicHolidaysService)
        {
            _logger = logger;
            _openCloseDaysService = openCloseDaysService;
            this.plafondSecuFetcher = plafondSecuFetcher;
            this.explainationManager = explainationManager;
            this.validator = validator;
            _publicHolidaysService = publicHolidaysService;

            Countries = _publicHolidaysService.GetHandledCountries().Select(c => new SelectListItem(c.name, c.code));
        }

        public async Task OnGetAsync()
        {
            await ComputeDaysAsync();
        }
        public async Task OnPostAsync()
        {
            await ComputeDaysAsync();
        }
        public async Task<FileResult> OnGetExcelAsync()
        {
            await ComputeDaysAsync();

            var excelBytes = await StageExcel.GenerateExcel(Result, PayRate.ParseAsFloat());
            var fileName = $"Calcul durée et gratification de stage du {Result.StartDate:dd/MM/yyyy} au {Result.EndDate:dd/MM/yyyy}.xlsx";
            return File(excelBytes,
                StageExcel.XLSX_Mimetype,
                fileName);
        }

        private void EnsureStartBeforeEnd()
        {
            if (StartDate.Date > EndDate.Date)
            {
                var tmp = StartDate;
                StartDate = EndDate;
                EndDate = tmp;
            }
        }

        private async Task ComputeDaysAsync()
        {
            HolidayNames = _publicHolidaysService.GetPublicHolidaysForYear(Country, DateTime.Now.Year).Select(h => new SelectListItem($"{h.Value} ({h.Key.ToString("dd/MM/yyyy")})", h.Value));
			
            foreach (var error in validator.Validate(this).Errors)
                ModelState.AddModelError(error.PropertyName, error.ErrorMessage);

            EnsureStartBeforeEnd();

            explainationManager.RegisterVariable("taux-horaire", (await plafondSecuFetcher.GetLegalStagePayRateAsync(StartDate)).ToString("0.00",CultureInfo.InvariantCulture));
            explainationManager.RegisterVariable("taux-horaire_année", StartDate.Year.ToString());
            explainationManager.RegisterVariable("duree-legale", StageLegislation.LongStage_Hours.ToString());
            explainationManager.RegisterVariable("duree-legale-plus", (StageLegislation.LongStage_Hours + 1).ToString());
            explainationManager.RegisterVariable("pourcent-phss", (StageLegislation.LEGAL_PAYRATE_PLAFOND_RATIO * 100).ToString("0.#"));

            Result = _openCloseDaysService.ComputeWorkDays(
                Country, StartDate, EndDate, new DaysWorkHours()
                {
                    MondayWorkHours = MondayWorkHours,
                    MondayWorkMinutes = MondayWorkMinutes,
                    TuesdayWorkHours = TuesdayWorkHours,
                    TuesdayWorkMinutes = TuesdayWorkMinutes,
                    WednesdayWorkHours = WednesdayWorkHours,
                    WednesdayWorkMinutes = WednesdayWorkMinutes,
                    ThursdayWorkHours = ThursdayWorkHours,
                    ThursdayWorkMinutes = ThursdayWorkMinutes,
                    FridayWorkHours = FridayWorkHours,
                    FridayWorkMinutes = FridayWorkMinutes,
                    SaturdayWorkHours = SaturdayWorkHours,
                    SaturdayWorkMinutes = SaturdayWorkMinutes,
                    SundayWorkHours = SundayWorkHours,
                    SundayWorkMinutes = SundayWorkMinutes,
                },
                WorkPublicHolidays.ToArray(), null, ExcludedDateTimes.ToArray());

            await StageLegislation.EnsureLegislationForPayRateAsync(
                plafondSecuFetcher, StartDate,
                PayRate.ParseAsFloat(), EnterpriseType, StageCountry, TrainingType,
                Result.TotalOpenHours, async (newRate, messsage) =>
                {
                    PayRate = newRate.ToString(CultureInfo.InvariantCulture);
                    ModelState.AddModelError(nameof(PayRate),
                        messsage);
                });

            if (!StageLegislation.IsInAllowedHours(Result.TotalOpenHours))
            {
                ModelState.AddModelError(nameof(Result),
                    StageLegislation.GetTooLongStageHoursMessage());
            }

            LongStageStartDate = StageLegislation.GetLongStageStartDate(Result);
        }

        public IEnumerable<DateTime> ExcludedDateTimes
            => ExcludedDates.ParseAsDatesList();
    }
}

StageComputer/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StageComputer.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

StageComputer/Pages/Index.cshtml
@page "{handler?}"
@using OpenCloseDays.Extensions
@using StageComputer.Utils
@inject StageComputer.Utils.ExplainationManager explainationManager
@model StageComputerModel
@{
	ViewData["Title"] = "Simulateur de calcul de la durée et de la gratification de stage";

	var payRate = Model.PayRate.ParseAsFloat();
}

<div class="text-center mb-5 mt-4">
	<h1 class="display-5">@ViewData["Title"]</h1>
</div>

<div class="mb-4 mt-5">
	@await explainationManager.GetExplainationHtmlAsync("general")
	<details class="explaination">
		<summary class="text-decoration-underline"><em>En savoir plus sur la gratification</em></summary>
		@await explainationManager.GetExplainationHtmlAsync("general_details")
	</details>
</div>

<form method="get">
	@if (!ModelState.IsValid)
	{
		<div class="alert-danger" aria-label="Erreurs dans le formulaire">
			<div asp-validation-summary="All"></div>
		</div>
	}

	<div class="row">
		<div class="form-floating col-md-4">
			<input class="form-control resetpayrate" name="s" type="date" asp-for="StartDate" />
			<label class="" asp-for="StartDate"></label>
		</div>
		<div class="form-floating col-md-4">
			<input class="form-control resetpayrate" name="e" type="date" asp-for="EndDate" />
			<label class="" asp-for="EndDate"></label>
		</div>
		<div class="form-floating col-md-4">
			<select class="form-select resetpayrate" name="c" asp-for="Country" asp-items="Model.Countries"></select>
			<label class="" asp-for="Country"></label>
		</div>
	</div>

	<div class="border rounded mt-1">
		<fieldset class="p-1" aria-labelledby="paysLegend">
			<div class="row">
				<legend class="col-md-2 fs-6" id="paysLegend">
					Pays
				</legend>
				<div class="form-group col-md-10">
					<div class="form-check form-check-inline">
						<input id="radInFrance" class="form-check-input resetpayrate" type="radio"
							   asp-for="StageCountry" name="stc" value="@StageLegislation.IN_FRANCE" />
						<label for="radInFrance">Stage en France</label>
					</div>
					<div class="form-check form-check-inline">
						<input id="radForeign" class="form-check-input resetpayrate" type="radio"
							   asp-for="StageCountry" name="stc" value="@StageLegislation.OUTSIDE_FRANCE" />
						<label for="radForeign">Stage à l’étranger</label>
					</div>
				</div>
			</div>
		</fieldset>
		<hr />
		<fieldset class="p-1" aria-labelledby="organismLegend">
			<div class="row">
				<legend class="col-md-2 fs-6" id="organismLegend">
					Organisme d’accueil
				</legend>
				<div class="form-group col-md-10">
					<div class="form-check form-check-inline">
						<input id="radPrivate" class="form-check-input resetpayrate" type="radio"
							   asp-for="EnterpriseType" name="ent" value="@StageLegislation.ENTERPRISE_TYPE_PRIVATE" />
						<label for="radPrivate">Organisme de droit privé</label>
					</div>
					<div class="form-check form-check-inline">
						<input id="radPublic" class="form-check-input resetpayrate" type="radio"
							   asp-for="EnterpriseType" name="ent" value="@StageLegislation.ENTERPRISE_TYPE_PUBLIC" />
						<label for="radPublic">Organisme de droit public</label>
					</div>
				</div>
			</div>
		</fieldset>
		<hr />
		<fieldset class="p-1" aria-labelledby="formationLegend">
			<div class="row">
				<legend class="col-md-2 fs-6" id="formationLegend">
					Formation
				</legend>
				<div class="form-group col-md-10">
					<div class="form-check form-check-inline">
						<input id="radTTMedical" class="form-check-input resetpayrate" type="radio"
							   asp-for="TrainingType" name="tt" value="@StageLegislation.TRAINING_MEDICAL" />
						<label for="radTTMedical">Formation d’auxiliaire médical (infirmier, masseur-kinésithérapeute rééducateur, pédicure, orthophoniste, orthoptiste)</label>
					</div>
					<div class="form-check form-check-inline">
						<input id="radTTOther" class="form-check-input resetpayrate" type="radio"
							   asp-for="TrainingType" name="tt" value="@StageLegislation.TRAINING_OTHER" />
						<label for="radTTOther">Autre formation</label>
					</div>
				</div>
			</div>
		</fieldset>
	</div>

	<div class="accordion mt-3" id="optionsAccordion">
		<div class="accordion-item">
			<h2 class="accordion-header" id="weekdaysHeader">
				<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#weekdaysCollapse" aria-expanded="false" aria-controls="weekdaysCollapse">
					Heures de présence effective du stagiaire dans l’organisme d’accueil
				</button>
			</h2>
			<div id="weekdaysCollapse" class="accordion-collapse collapse" aria-labelledby="weekdaysHeader" data-bs-parent="#optionsAccordion">
				<div class="accordion-body container">
					<div class="row">
						<div class="explaination col-md-12 text-center">
							Nombre d’heures de présence par jour du stagiaire dans l’organisme d’accueil
						</div>
					</div>
					<div class="row justify-content-evenly row-smaller">
						<div class="form-group col-md-2 col-xs-6">
							<label class="text-nowrap" asp-for="MondayWorkHours"></label>
							<div class="input-group">
								<input class="form-control workhours" name="monh" min="0" max="23" asp-for="MondayWorkHours" aria-label="Lundi - Heures de travail" />
								<span class="input-group-text" id="basic-addon1">h</span>
								<input class="form-control workminutes" name="monm" min="0" max="59" asp-for="MondayWorkMinutes" aria-label="Lundi - Minutes de travail" />
							</div>
						</div>
						<div class="form-group col-md-2 col-xs-6">
							<label class="text-nowrap" asp-for="TuesdayWorkHours"></label>
							<div class="input-group">
								<input class="form-control workhours" name="tueh" min="0" max="23" asp-for="TuesdayWorkHours" aria-label="Mardi - Heures de travail" />
								<span class="input-group-text" id="basic-addon1">h</span>
								<input class="form-control workminutes" name="tuem" min="0" max="59" asp-for="TuesdayWorkMinutes" aria-label="Mardi - Minutes de travail" />
							</div>
						</div>
						<div class="form-group col-md-2 col-xs-6">
							<label class="text-nowrap" asp-for="WednesdayWorkHours"></label>
							<div class="input-group">
								<input class="form-control workhours" name="wedh" min="0" max="23" asp-for="WednesdayWorkHours" aria-label="Mercredi - Heures de travail" />
								<span class="input-group-text" id="basic-addon1">h</span>
								<input class="form-control workminutes" name="wedm" min="0" max="59" asp-for="WednesdayWorkMinutes" aria-label="Mercredi - Minutes de travail" />
							</div>
						</div>
						<div class="form-group col-md-2 col-xs-6">
							<label class="text-nowrap" asp-for="ThursdayWorkHours"></label>
							<div class="input-group">
								<input class="form-control workhours" name="thuh" min="0" max="23" asp-for="ThursdayWorkHours" aria-label="Jeudi - Heures de travail" />
								<span class="input-group-text" id="basic-addon1">h</span>
								<input class="form-control workminutes" name="thum" min="0" max="59" asp-for="ThursdayWorkMinutes" aria-label="Jeudi - Minutes de travail" />
							</div>
						</div>
						<div class="form-group col-md-2 col-xs-6">
							<label class="text-nowrap" asp-for="FridayWorkHours"></label>
							<div class="input-group">
								<input class="form-control workhours" name="frih" min="0" max="23" asp-for="FridayWorkHours" aria-label="Vendredi - Heures de travail" />
								<span class="input-group-text" id="basic-addon1">h</span>
								<input class="form-control workminutes" name="frim" min="0" max="59" asp-for="FridayWorkMinutes" aria-label="Vendredi - Minutes de travail" />
							</div>
						</div>
					</div>
					<div class="row justify-content-center row-smaller">
						<div class="form-group col-md-2 col-xs-6">
							<label class="text-nowrap" asp-for="SaturdayWorkHours"></label>
							<div class="input-group">
								<input class="form-control workhours" name="sath" min="0" max="23" asp-for="SaturdayWorkHours" aria-label="Samedi - Heures de travail" />
								<span class="input-group-text" id="basic-addon1">h</span>
								<input class="form-control workminutes" name="satm" min="0" max="59" asp-for="SaturdayWorkMinutes" aria-label="Samedi - Minutes de travail" />
							</div>
						</div>
						<div class="form-group col-md-2 col-xs-6">
							<label class="text-nowrap" asp-for="SundayWorkHours"></label>
							<div class="input-group">
								<input class="form-control workhours" name="sunh" min="0" max="23" asp-for="SundayWorkHours" aria-label="Dimanche - Heures de travail" />
								<span class="input-group-text" id="basic-addon1">h</span>
								<input class="form-control workminutes" name="sunm" min="0" max="59" asp-for="SundayWorkMinutes" aria-label="Dimanche - Minutes de travail" />
							</div>
						</div>
					</div>
					<div class="row">
						<p><strong>Volume horaire hebdomadaire : <span id="hoursInfo"></span></strong></p>
					</div>
					<div class="row">
						<div class="explaination col-md-12">
							@await explainationManager.GetExplainationHtmlAsync("workhours")
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="accordion-item">
			<h2 class="accordion-header" id="excludedHeader">
				<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#excludedCollapse" aria-expanded="false" aria-controls="excludedCollapse">
					Indiquez ici vos jours d’absence et périodes d’interruption de stage (hors jours fériés)
				</button>
			</h2>
			<div id="excludedCollapse" class="accordion-collapse collapse" aria-labelledby="excludedHeader" data-bs-parent="#optionsAccordion">
				<div class="accordion-body container">
					<div class="row">
						<div class="explaination col-md-12">
							@await explainationManager.GetExplainationHtmlAsync("excludeddays")
						</div>
					</div>
					<div class="row">
						<div class="form-group col-md-6">
							<label class="" for="ExcludedDatePicker">Sélectionner les jours où vous n’êtes pas en stage</label>
							<input class="form-control" readonly="readonly" placeholder="Dates à exclure" type="text" autocomplete="off" id="ExcludedDatePicker" />
							<input type="hidden" asp-for="ExcludedDates" name="excl" />
						</div>
						<div class="form-group col-md-6">
							<label class="" asp-for="WorkPublicHolidays"></label>
							<select class="form-select sl2" multiple="multiple" asp-for="WorkPublicHolidays" name="wph" asp-items="Model.HolidayNames"></select>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="accordion-item">
			<h2 class="accordion-header" id="rateHeader">
				<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#rateCollapse" aria-expanded="false" aria-controls="rateCollapse">
					Montant de la gratification (<span id="payrateInfo"></span>€/h)
				</button>
			</h2>
			<div id="rateCollapse" class="accordion-collapse collapse" aria-labelledby="rateHeader" data-bs-parent="#optionsAccordion">
				<div class="accordion-body container">
					<div class="row">
						<div class="explaination col-md-12">
							@await explainationManager.GetExplainationHtmlAsync("payrate")
						</div>
					</div>
					<div class="row">
						<div class="form-group col-md-12">
							<div class="input-group">
								<div class="input-group-prepend">
									<label class="input-group-text" asp-for="PayRate"></label>
								</div>
								<input class="form-control" asp-for="PayRate" name="r" type="number" step="0.01" min="0" />
								<span class="input-group-text">€/h</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row g-2 mt-3 text-center">
		<div class="col">
			<input class="btn btn-primary" type="submit" value="Calculer" />
		</div>
	</div>

	<div class="row mt-3">
		<div id="exportExcelExplain">
			@await explainationManager.GetExplainationHtmlAsync("exportexcel")
		</div>
	</div>
	<div class="row text-center">
		<div class="col">
			<input class="btn btn-secondary ml-2" style="display:inline-block;width:auto;vertical-align: baseline" type="submit" asp-page-handler="Excel" value="Export Excel" aria-labelledby="exportExcelExplain" />
		</div>
	</div>
</form>

@if (!ModelState.IsValid)
{
	<div class="alert-danger" style="margin-top: 1em" aria-label="Erreurs dans le formulaire">
		<div asp-validation-summary="All"></div>
	</div>
}

<section id="refresh-needed" style="display:none">
	<p class="text-center mt-5 fw-bold alert-warning">Les informations du formulaire ont été changées. Merci de cliquer sur le bouton Calculer pour obtenir le résultat à jour.</p>
</section>

@if (StageLegislation.IsInAllowedHours(Model.Result?.TotalOpenHours ?? 0)){
	await Html.RenderPartialAsync("_Result", Model);
}

@section Scripts{
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}